server.port=8083

spring.application.name=location-service
eureka.client.service-url.defaultZone=http://localhost:8085/eureka/

weather.url=weather-info-service:8082

spring.datasource.url=jdbc:h2:file:./location/db
spring.datasource.username=location_service
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

appId=89f4431c2e43cf3810482b26330f2d18
url.weather=https://api.openweathermap.org/data/2.5/weather



