server.port=8082
spring.application.name=weather-info-service
appId=89f4431c2e43cf3810482b26330f2d18
url.weather=https://api.openweathermap.org/data/2.5/weather
eureka.client.service-url.defaultZone=http://localhost:8085/eureka/
